name: Terraform GCP

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'infra/**'
      - '.github/workflows/terraform-gcp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'infra/**'
      - '.github/workflows/terraform-gcp.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_BACKEND_BUCKET: tf-state-cnn-hybrid-experiments-infra
  TF_VARS_FILE_ABS: ${{ github.workspace }}/infra/envs/common.tfvars

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfdir:
          - infra/foundation
          - infra/experiments/cnn-fnn
          - infra/experiments/cnn-mlp
          - infra/experiments/cnn-mfcc
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Sanity check backend bucket
        run: gcloud storage buckets describe gs://${{ env.TF_BACKEND_BUCKET }} --format='value(name)'

      - name: Terraform Init
        working-directory: ${{ matrix.tfdir }}
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="prefix=${{ matrix.tfdir }}"

      - name: Terraform Fmt
        working-directory: ${{ matrix.tfdir }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ matrix.tfdir }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.tfdir }}
        run: |
          if [ -f "${{ env.TF_VARS_FILE_ABS }}" ]; then
            terraform plan -input=false -out=tfplan -var-file="${{ env.TF_VARS_FILE_ABS }}"
          else
            terraform plan -input=false -out=tfplan
          fi
          terraform show -no-color tfplan > tfplan.txt

      - name: Comment plan
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const p = `${process.env.GITHUB_WORKSPACE}/${{ matrix.tfdir }}/tfplan.txt`;
            const body = fs.readFileSync(p,'utf8').slice(0, 60000);
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `### Plan \`${{ matrix.tfdir }}\`\n\`\`\`hcl\n${body}\n\`\`\``
            });

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        tfdir:
          - infra/foundation
          - infra/experiments/cnn-fnn
          - infra/experiments/cnn-mlp
          - infra/experiments/cnn-mfcc
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ matrix.tfdir }}
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="prefix=${{ matrix.tfdir }}/env/prod"

      - name: Terraform Plan (safety)
        working-directory: ${{ matrix.tfdir }}
        run: |
          if [ -f "${{ env.TF_VARS_FILE_ABS }}" ]; then
            terraform plan -input=false -out=tfplan -var-file="${{ env.TF_VARS_FILE_ABS }}"
          else
            terraform plan -input=false -out=tfplan
          fi

      - name: Terraform Apply
        working-directory: ${{ matrix.tfdir }}
        run: terraform apply -auto-approve tfplan


  build_apps:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ kaggle-upload] # <--- list of projects
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Get region
        run: echo "REGION=$(gcloud config get-value compute/region)" >> $GITHUB_ENV


      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & Push
        run: |
          IMAGE_URI="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-experiments/${{ matrix.app }}:${{ github.sha }}"
          docker build -t "$IMAGE_URI" "apps/${{ matrix.app }}"
          docker push "$IMAGE_URI"
          docker tag "$IMAGE_URI" $REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-experiments/${{ matrix.app }}:latest"
          docker push "$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-experiments/${{ matrix.app }}:latest"
